apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boomi-molecule.fullname" . }}
  labels:
    {{- include "boomi-molecule.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "Molecule Installer Token is required." .Values.runtime.token }}

