apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boomi-atom.fullname" . }}
  labels:
    {{- include "boomi-atom.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "Atom Installer Token is required." .Values.runtime.token }}

